### PR TITLE
Feature/cron

### PR DESCRIPTION
**Pull request by ReedD**
```
node index.js
```

Runs just as it would before

```
forever start index.js
```

Starts up a cron that triggers a notification center alert Monday through Friday at 9:30am (by default). The cron can obviously be changed to any interval with the config. If you click the alert, your default hours will be added. If the alert is ignored nothing happens.

### CODE REVIEW

**Comment by ReedD** [comment]
Oh yeah, it also uses Redis to avoid duplicates or repeat notifications. So you could set the cron to remind you every couple of hours Mon-Fri and if you enter your hours for that day, it will stop asking.

**Comment by jmillerdesign** [comment]
Awesome. Thanks!

**Comment by jmillerdesign** [comment]
Is `forever` necessary to keep the script running, to handle the notification center feedback, or could it use the system's native crontab?

**Comment by ReedD** [comment]
Yeah you could use the crontab binary, however you'd need to modify it so that the script accepted some sort of argument flag to indicate that it was running via cron. I looked into the resource usage of forever and node and they both consume 0.00000% cpu the 99% of the time because their processes are usually in the `sleep` state. However, they do use a small amount of memory.

**Pull request merged**
